//! The CAMEO event codes GDELT uses, in words.
//!
//! CAMEO (Conflict and Mediation Event Observations) codes what one actor
//! did to another: twenty root classes from "make public statement" to
//! "use unconventional mass violence", each refined to three- and
//! four-digit codes. GDELT tags every event with one. The table is CAMEO
//! 1.1b3 as GDELT's own codebook lists it; a code that is not here reads
//! as its root, so a new or odd code is never a blank card.

/// The twenty root classes.
pub const ROOTS: &[(&str, &str)] = &[
    ("01", "make public statement"),
    ("02", "appeal"),
    ("03", "express intent to cooperate"),
    ("04", "consult"),
    ("05", "engage in diplomatic cooperation"),
    ("06", "engage in material cooperation"),
    ("07", "provide aid"),
    ("08", "yield"),
    ("09", "investigate"),
    ("10", "demand"),
    ("11", "disapprove"),
    ("12", "reject"),
    ("13", "threaten"),
    ("14", "protest"),
    ("15", "exhibit force posture"),
    ("16", "reduce relations"),
    ("17", "coerce"),
    ("18", "assault"),
    ("19", "fight"),
    ("20", "use unconventional mass violence"),
];

/// Every three- and four-digit code.
pub const CODES: &[(&str, &str)] = &[
    ("010", "make statement, not specified below"),
    ("011", "decline comment"),
    ("012", "make pessimistic comment"),
    ("013", "make optimistic comment"),
    ("014", "consider policy option"),
    ("015", "acknowledge or claim responsibility"),
    ("016", "deny responsibility"),
    ("017", "engage in symbolic act"),
    ("018", "make empathetic comment"),
    ("019", "express accord"),
    ("020", "appeal, not specified below"),
    ("021", "appeal for material cooperation"),
    ("0211", "appeal for economic cooperation"),
    ("0212", "appeal for military cooperation"),
    ("0213", "appeal for judicial cooperation"),
    ("0214", "appeal for intelligence cooperation"),
    ("022", "appeal for diplomatic cooperation, such as policy support"),
    ("023", "appeal for aid"),
    ("0231", "appeal for economic aid"),
    ("0232", "appeal for military aid"),
    ("0233", "appeal for humanitarian aid"),
    ("0234", "appeal for military protection or peacekeeping"),
    ("024", "appeal for political reform"),
    ("0241", "appeal for change in leadership"),
    ("0242", "appeal for policy change"),
    ("0243", "appeal for rights"),
    ("0244", "appeal for change in institutions or regime"),
    ("025", "appeal to yield"),
    ("0251", "appeal for easing of administrative sanctions"),
    ("0252", "appeal for easing of popular dissent"),
    ("0253", "appeal for release of persons or property"),
    ("0254", "appeal for easing of economic sanctions, boycott or embargo"),
    ("0255", "appeal for target to allow international involvement"),
    ("0256", "appeal for de-escalation of military engagement"),
    ("026", "appeal to others to meet or negotiate"),
    ("027", "appeal to others to settle dispute"),
    ("028", "appeal to others to engage in or accept mediation"),
    ("030", "express intent to cooperate, not specified below"),
    ("031", "express intent to engage in material cooperation"),
    ("0311", "express intent to cooperate economically"),
    ("0312", "express intent to cooperate militarily"),
    ("0313", "express intent to cooperate on judicial matters"),
    ("0314", "express intent to cooperate on intelligence"),
    ("032", "express intent to engage in diplomatic cooperation"),
    ("033", "express intent to provide material aid"),
    ("0331", "express intent to provide economic aid"),
    ("0332", "express intent to provide military aid"),
    ("0333", "express intent to provide humanitarian aid"),
    ("0334", "express intent to provide military protection or peacekeeping"),
    ("034", "express intent to institute political reform"),
    ("0341", "express intent to change leadership"),
    ("0342", "express intent to change policy"),
    ("0343", "express intent to provide rights"),
    ("0344", "express intent to change institutions or regime"),
    ("035", "express intent to yield"),
    ("0351", "express intent to ease administrative sanctions"),
    ("0352", "express intent to ease popular dissent"),
    ("0353", "express intent to release persons or property"),
    ("0354", "express intent to ease economic sanctions, boycott or embargo"),
    ("0355", "express intent to allow international involvement"),
    ("0356", "express intent to de-escalate military engagement"),
    ("036", "express intent to meet or negotiate"),
    ("037", "express intent to settle dispute"),
    ("038", "express intent to accept mediation"),
    ("039", "express intent to mediate"),
    ("040", "consult, not specified below"),
    ("041", "discuss by telephone"),
    ("042", "make a visit"),
    ("043", "host a visit"),
    ("044", "meet at a third location"),
    ("045", "mediate"),
    ("046", "engage in negotiation"),
    ("050", "engage in diplomatic cooperation, not specified below"),
    ("051", "praise or endorse"),
    ("052", "defend verbally"),
    ("053", "rally support on behalf of"),
    ("054", "grant diplomatic recognition"),
    ("055", "apologize"),
    ("056", "forgive"),
    ("057", "sign formal agreement"),
    ("060", "engage in material cooperation, not specified below"),
    ("061", "cooperate economically"),
    ("062", "cooperate militarily"),
    ("063", "engage in judicial cooperation"),
    ("064", "share intelligence or information"),
    ("070", "provide aid, not specified below"),
    ("071", "provide economic aid"),
    ("072", "provide military aid"),
    ("073", "provide humanitarian aid"),
    ("074", "provide military protection or peacekeeping"),
    ("075", "grant asylum"),
    ("080", "yield, not specified below"),
    ("081", "ease administrative sanctions"),
    ("0811", "ease restrictions on political freedoms"),
    ("0812", "ease ban on political parties or politicians"),
    ("0813", "ease curfew"),
    ("0814", "ease state of emergency or martial law"),
    ("082", "ease political dissent"),
    ("083", "accede to requests or demands for political reform"),
    ("0831", "accede to demands for change in leadership"),
    ("0832", "accede to demands for change in policy"),
    ("0833", "accede to demands for rights"),
    ("0834", "accede to demands for change in institutions or regime"),
    ("084", "return or release"),
    ("0841", "return or release persons"),
    ("0842", "return or release property"),
    ("085", "ease economic sanctions, boycott or embargo"),
    ("086", "allow international involvement"),
    ("0861", "receive deployment of peacekeepers"),
    ("0862", "receive inspectors"),
    ("0863", "allow humanitarian access"),
    ("087", "de-escalate military engagement"),
    ("0871", "declare truce or ceasefire"),
    ("0872", "ease military blockade"),
    ("0873", "demobilize armed forces"),
    ("0874", "retreat or surrender militarily"),
    ("090", "investigate, not specified below"),
    ("091", "investigate crime or corruption"),
    ("092", "investigate human rights abuses"),
    ("093", "investigate military action"),
    ("094", "investigate war crimes"),
    ("100", "demand, not specified below"),
    ("101", "demand material cooperation"),
    ("1011", "demand economic cooperation"),
    ("1012", "demand military cooperation"),
    ("1013", "demand judicial cooperation"),
    ("1014", "demand intelligence cooperation"),
    ("102", "demand diplomatic cooperation, such as policy support"),
    ("103", "demand material aid"),
    ("1031", "demand economic aid"),
    ("1032", "demand military aid"),
    ("1033", "demand humanitarian aid"),
    ("1034", "demand military protection or peacekeeping"),
    ("104", "demand political reform"),
    ("1041", "demand change in leadership"),
    ("1042", "demand policy change"),
    ("1043", "demand rights"),
    ("1044", "demand change in institutions or regime"),
    ("105", "demand that target yields"),
    ("1051", "demand easing of administrative sanctions"),
    ("1052", "demand easing of political dissent"),
    ("1053", "demand release of persons or property"),
    ("1054", "demand easing of economic sanctions, boycott or embargo"),
    ("1055", "demand that target allows international involvement"),
    ("1056", "demand de-escalation of military engagement"),
    ("106", "demand meeting or negotiation"),
    ("107", "demand settling of dispute"),
    ("108", "demand mediation"),
    ("110", "disapprove, not specified below"),
    ("111", "criticize or denounce"),
    ("112", "accuse"),
    ("1121", "accuse of crime or corruption"),
    ("1122", "accuse of human rights abuses"),
    ("1123", "accuse of aggression"),
    ("1124", "accuse of war crimes"),
    ("1125", "accuse of espionage or treason"),
    ("113", "rally opposition against"),
    ("114", "complain officially"),
    ("115", "bring lawsuit against"),
    ("116", "find guilty or liable"),
    ("120", "reject, not specified below"),
    ("121", "reject material cooperation"),
    ("1211", "reject economic cooperation"),
    ("1212", "reject military cooperation"),
    ("122", "reject request or demand for material aid"),
    ("1221", "reject request for economic aid"),
    ("1222", "reject request for military aid"),
    ("1223", "reject request for humanitarian aid"),
    ("1224", "reject request for military protection or peacekeeping"),
    ("123", "reject request or demand for political reform"),
    ("1231", "reject request for change in leadership"),
    ("1232", "reject request for policy change"),
    ("1233", "reject request for rights"),
    ("1234", "reject request for change in institutions or regime"),
    ("124", "refuse to yield"),
    ("1241", "refuse to ease administrative sanctions"),
    ("1242", "refuse to ease popular dissent"),
    ("1243", "refuse to release persons or property"),
    ("1244", "refuse to ease economic sanctions, boycott or embargo"),
    ("1245", "refuse to allow international involvement"),
    ("1246", "refuse to de-escalate military engagement"),
    ("125", "reject proposal to meet, discuss or negotiate"),
    ("126", "reject mediation"),
    ("127", "reject plan or agreement to settle dispute"),
    ("128", "defy norms or law"),
    ("129", "veto"),
    ("130", "threaten, not specified below"),
    ("131", "threaten non-force"),
    ("1311", "threaten to reduce or stop aid"),
    ("1312", "threaten with sanctions, boycott or embargo"),
    ("1313", "threaten to reduce or break relations"),
    ("132", "threaten with administrative sanctions"),
    ("1321", "threaten with restrictions on political freedoms"),
    ("1322", "threaten to ban political parties or politicians"),
    ("1323", "threaten to impose curfew"),
    ("1324", "threaten to impose state of emergency or martial law"),
    ("133", "threaten with political dissent or protest"),
    ("134", "threaten to halt negotiations"),
    ("135", "threaten to halt mediation"),
    ("136", "threaten to halt international involvement"),
    ("137", "threaten with repression"),
    ("138", "threaten with military force"),
    ("1381", "threaten blockade"),
    ("1382", "threaten occupation"),
    ("1383", "threaten unconventional violence"),
    ("1384", "threaten conventional attack"),
    ("1385", "threaten attack with weapons of mass destruction"),
    ("139", "give ultimatum"),
    ("140", "engage in political dissent, not specified below"),
    ("141", "demonstrate or rally"),
    ("1411", "demonstrate for leadership change"),
    ("1412", "demonstrate for policy change"),
    ("1413", "demonstrate for rights"),
    ("1414", "demonstrate for change in institutions or regime"),
    ("142", "conduct hunger strike"),
    ("1421", "conduct hunger strike for leadership change"),
    ("1422", "conduct hunger strike for policy change"),
    ("1423", "conduct hunger strike for rights"),
    ("1424", "conduct hunger strike for change in institutions or regime"),
    ("143", "conduct strike or boycott"),
    ("1431", "conduct strike or boycott for leadership change"),
    ("1432", "conduct strike or boycott for policy change"),
    ("1433", "conduct strike or boycott for rights"),
    ("1434", "conduct strike or boycott for change in institutions or regime"),
    ("144", "obstruct passage or block"),
    ("1441", "obstruct passage to demand leadership change"),
    ("1442", "obstruct passage to demand policy change"),
    ("1443", "obstruct passage to demand rights"),
    ("1444", "obstruct passage to demand change in institutions or regime"),
    ("145", "protest violently or riot"),
    ("1451", "engage in violent protest for leadership change"),
    ("1452", "engage in violent protest for policy change"),
    ("1453", "engage in violent protest for rights"),
    ("1454", "engage in violent protest for change in institutions or regime"),
    ("150", "demonstrate military or police power, not specified below"),
    ("151", "increase police alert status"),
    ("152", "increase military alert status"),
    ("153", "mobilize or increase police power"),
    ("154", "mobilize or increase armed forces"),
    ("155", "mobilize or increase cyber-forces"),
    ("160", "reduce relations, not specified below"),
    ("161", "reduce or break diplomatic relations"),
    ("162", "reduce or stop material aid"),
    ("1621", "reduce or stop economic assistance"),
    ("1622", "reduce or stop military assistance"),
    ("1623", "reduce or stop humanitarian assistance"),
    ("163", "impose embargo, boycott or sanctions"),
    ("164", "halt negotiations"),
    ("165", "halt mediation"),
    ("166", "expel or withdraw"),
    ("1661", "expel or withdraw peacekeepers"),
    ("1662", "expel or withdraw inspectors or observers"),
    ("1663", "expel or withdraw aid agencies"),
    ("170", "coerce, not specified below"),
    ("171", "seize or damage property"),
    ("1711", "confiscate property"),
    ("1712", "destroy property"),
    ("172", "impose administrative sanctions"),
    ("1721", "impose restrictions on political freedoms"),
    ("1722", "ban political parties or politicians"),
    ("1723", "impose curfew"),
    ("1724", "impose state of emergency or martial law"),
    ("173", "arrest, detain or charge with legal action"),
    ("174", "expel or deport individuals"),
    ("175", "use tactics of violent repression"),
    ("176", "attack cybernetically"),
    ("180", "use unconventional violence, not specified below"),
    ("181", "abduct, hijack or take hostage"),
    ("182", "physically assault"),
    ("1821", "sexually assault"),
    ("1822", "torture"),
    ("1823", "kill by physical assault"),
    ("183", "conduct suicide, car or other non-military bombing"),
    ("1831", "carry out suicide bombing"),
    ("1832", "carry out vehicular bombing"),
    ("1833", "carry out roadside bombing"),
    ("1834", "carry out location bombing"),
    ("184", "use as human shield"),
    ("185", "attempt to assassinate"),
    ("186", "assassinate"),
    ("190", "use conventional military force, not specified below"),
    ("191", "impose blockade or restrict movement"),
    ("192", "occupy territory"),
    ("193", "fight with small arms and light weapons"),
    ("194", "fight with artillery and tanks"),
    ("195", "employ aerial weapons"),
    ("1951", "employ precision-guided aerial munitions"),
    ("1952", "employ remotely piloted aerial munitions"),
    ("196", "violate ceasefire"),
    ("200", "use unconventional mass violence, not specified below"),
    ("201", "engage in mass expulsion"),
    ("202", "engage in mass killings"),
    ("203", "engage in ethnic cleansing"),
    ("204", "use weapons of mass destruction"),
    ("2041", "use chemical, biological or radiological weapons"),
    ("2042", "detonate nuclear weapons"),
];

/// The words for a code: the exact code, else its root, else nothing.
pub fn words(code: &str) -> Option<&'static str> {
    let code = code.trim();
    if let Some((_, w)) = CODES.iter().find(|(c, _)| *c == code) {
        return Some(w);
    }
    let root = code.get(..2)?;
    ROOTS.iter().find(|(c, _)| *c == root).map(|(_, w)| *w)
}

/// The root class's words.
pub fn root_words(root: &str) -> Option<&'static str> {
    ROOTS.iter().find(|(c, _)| *c == root.trim()).map(|(_, w)| *w)
}

/// GDELT's quad class: which quadrant of cooperation and conflict.
pub fn quad_words(quad: &str) -> Option<&'static str> {
    match quad.trim() {
        "1" => Some("verbal cooperation"),
        "2" => Some("material cooperation"),
        "3" => Some("verbal conflict"),
        "4" => Some("material conflict"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_code_has_a_root_and_no_code_is_listed_twice() {
        let mut seen = std::collections::HashSet::new();
        for (code, w) in CODES {
            assert!(seen.insert(*code), "{code} twice");
            assert!(root_words(&code[..2]).is_some(), "{code} has no root");
            assert!(!w.is_empty());
        }
        assert_eq!(ROOTS.len(), 20);
        assert!(CODES.len() > 280, "{} codes", CODES.len());
    }

    #[test]
    fn an_unknown_subcode_reads_as_its_root() {
        assert_eq!(words("1823"), Some("kill by physical assault"));
        assert_eq!(words("043"), Some("host a visit"));
        assert_eq!(words("1999"), Some("fight"));
        assert_eq!(words("99"), None);
        assert_eq!(quad_words("4"), Some("material conflict"));
    }
}
